from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


TOKEN_RE = re.compile(r"[A-Za-z0-9]{3,}")


@dataclass(slots=True)
class IndicatorMatch:
    indicator_key: str
    score: float
    matched_terms: list[str]
    polarity: str
    score_breakdown: dict[str, float] = field(default_factory=dict)


class SEWSDeterministicIndicatorMatcher:
    STOPWORDS = {
        "the", "and", "for", "with", "from", "that", "this",
        "warning", "indicator", "strategic", "risk", "activity",
        "event", "events", "evidence", "current", "change",
        "changes", "system", "monitoring", "assess", "assessment",
        "relevant", "related", "source", "sources", "energy",
        "security", "supply", "chain", "conflict", "military",
        "economic", "financial", "political", "humanitarian",
        "public", "health", "operations", "domain", "regional",
        "global", "report", "reports", "news",
    }

    CLASS_POLARITY = {
        "PRECURSOR": "SUPPORTING",
        "ACCELERANT": "SUPPORTING",
        "TRIGGER": "SUPPORTING",
        "CONTRA": "CONTRADICTING",
    }

    # Evidence generated by collectors or transport failures must never
    # become analytic observations.
    BLOCKED_EVIDENCE_PHRASES = {
        "fetch failed",
        "request failed",
        "collector error",
        "collection error",
        "connection error",
        "http error",
        "timed out",
        "timeout",
        "resource temporarily unavailable",
    }

    # These words are meaningful only when accompanied by a more specific
    # concept term. They cannot independently establish indicator relevance.
    WEAK_ANCHOR_TERMS = {
        "price",
        "prices",
        "market",
        "markets",
        "production",
        "volume",
        "volumes",
        "flow",
        "flows",
        "rate",
        "rates",
        "capacity",
        "increase",
        "decrease",
        "change",
        "changes",
    }

    @classmethod
    def _terms(cls, *values: Any) -> set[str]:
        output: set[str] = set()

        for value in values:
            if value is None:
                continue

            if isinstance(value, (list, tuple, set)):
                output |= cls._terms(*value)
                continue

            if isinstance(value, dict):
                output |= cls._terms(
                    *value.keys(),
                    *value.values(),
                )
                continue

            normalized = str(value).lower().replace("_", " ")

            output |= {
                token
                for token in TOKEN_RE.findall(normalized)
                if token not in cls.STOPWORDS
            }

        return output

    @staticmethod
    def _bounded(value: float) -> float:
        return max(0.0, min(1.0, value))

    @staticmethod
    def _parse_datetime(value: Any) -> datetime | None:
        if value is None:
            return None

        if isinstance(value, datetime):
            return value

        try:
            parsed = datetime.fromisoformat(
                str(value).replace("Z", "+00:00")
            )
            if parsed.tzinfo is None:
                parsed = parsed.replace(tzinfo=timezone.utc)
            return parsed
        except Exception:
            return None

    def _freshness_score(self, evidence: dict[str, Any]) -> float:
        timestamp = self._parse_datetime(
            evidence.get("observed_at")
            or evidence.get("published_at")
            or evidence.get("collected_at")
        )

        if timestamp is None:
            return 0.45

        age_hours = max(
            0.0,
            (
                datetime.now(timezone.utc)
                - timestamp.astimezone(timezone.utc)
            ).total_seconds()
            / 3600,
        )

        # Smooth decay: ~0.75 at 72 hours, ~0.50 at 7 days.
        return round(
            math.exp(-age_hours / (24 * 10)),
            6,
        )

    def _source_reliability(
        self,
        evidence: dict[str, Any],
    ) -> float:
        metadata = evidence.get("metadata") or {}

        raw = (
            evidence.get("source_reliability")
            or metadata.get("source_reliability")
            or metadata.get("reliability_score")
            or 70
        )

        try:
            value = float(raw)
        except Exception:
            value = 70.0

        return self._bounded(value / 100.0)

    def _corroboration_score(
        self,
        evidence: dict[str, Any],
    ) -> float:
        metadata = evidence.get("metadata") or {}

        raw = (
            evidence.get("source_diversity_count")
            or metadata.get("source_diversity_count")
            or 1
        )

        try:
            count = max(1, int(raw))
        except Exception:
            count = 1

        # Only distinct sources increase corroboration confidence.
        # Repeated reporting from the same source does not.
        return self._bounded((count - 1) / 3.0)

    @classmethod
    def _blocked_evidence(
        cls,
        evidence: dict[str, Any],
    ) -> bool:
        text = " ".join(
            str(value or "")
            for value in (
                evidence.get("title"),
                evidence.get("raw_text"),
            )
        ).lower()

        return any(
            phrase in text
            for phrase in cls.BLOCKED_EVIDENCE_PHRASES
        )

    @classmethod
    def _anchor_terms(
        cls,
        indicator_key: str,
    ) -> set[str]:
        """
        Extract the most concept-specific trailing terms from an indicator.

        Examples:
        GAS_PRICE_VOLATILITY -> {price, volatility}
        PIPELINE_FLOWS       -> {pipeline, flows}
        REFINERY_UTILIZATION -> {refinery, utilization}

        Domain prefixes are deliberately not used as anchors.
        """
        key = str(indicator_key or "")

        for suffix in (
            "_PRECURSOR",
            "_ACCELERANT",
            "_TRIGGER",
            "_CONTRA",
        ):
            if key.endswith(suffix):
                key = key[:-len(suffix)]
                break

        tokens = [
            token
            for token in cls._terms(key)
            if token != "ind"
        ]

        # The final two concept terms are normally the discriminating
        # concept in the global indicator taxonomy.
        return set(tokens[-2:])

    def _lexical_scores(
        self,
        *,
        evidence: dict[str, Any],
        indicator: dict[str, Any],
        mapping: dict[str, Any],
    ) -> tuple[float, float, list[str]]:
        metadata = evidence.get("metadata") or {}

        # IMPORTANT:
        # Do not tokenize the entire metadata object. Collector metadata
        # contains warning/query/routing terms and can create artificial
        # matches unrelated to the article itself.
        evidence_terms = self._terms(
            evidence.get("title"),
            evidence.get("raw_text"),
            metadata.get("keywords"),
            metadata.get("entities"),
            metadata.get("topics"),
            metadata.get("tags"),
        )

        specific_terms = self._terms(
            indicator.get("indicator_key"),
            indicator.get("name"),
            indicator.get("tags"),
            indicator.get("sector_scope"),
        )

        context_terms = self._terms(
            indicator.get("description"),
            mapping.get("rationale"),
        )

        specific_overlap = evidence_terms & specific_terms
        context_overlap = evidence_terms & context_terms

        anchor_terms = self._anchor_terms(
            indicator.get("indicator_key") or ""
        )
        anchor_overlap = evidence_terms & anchor_terms
        strong_anchor_overlap = (
            anchor_overlap - self.WEAK_ANCHOR_TERMS
        )

        # Require substantive overlap with either the specific indicator
        # vocabulary or its curated description/rationale.
        if not specific_overlap and not context_overlap:
            return 0.0, 0.0, []

        # Strong concept anchors are preferred, but natural-language
        # reporting often describes the same phenomenon using synonyms
        # rather than the exact indicator-key vocabulary.
        #
        # A match may therefore survive without a strong anchor only when
        # there is sufficient contextual agreement.
        if anchor_terms and not strong_anchor_overlap:
            if (
                len(anchor_overlap) < 2
                and len(context_overlap) < 1
                and len(specific_overlap) < 2
            ):
                return 0.0, 0.0, []

        # Reject isolated generic token matches. One indicator term is
        # acceptable only when reinforced by contextual evidence.
        if len(specific_overlap) < 2 and len(context_overlap) < 1:
            return 0.0, 0.0, []

        combined = sorted(
            specific_overlap | context_overlap
        )

        specific_score = self._bounded(
            len(specific_overlap)
            / max(2, min(6, len(specific_terms)))
        )

        context_score = self._bounded(
            len(context_overlap)
            / max(3, min(8, len(context_terms)))
        )

        # Deterministic semantic proxy. Specific indicator vocabulary
        # receives substantially more weight than general rationale text.
        semantic_proxy = self._bounded(
            specific_score * 0.75
            + context_score * 0.25
        )

        return (
            specific_score,
            semantic_proxy,
            combined,
        )

    @staticmethod
    def _concept_key(indicator_key: str) -> str:
        for suffix in (
            "_PRECURSOR",
            "_ACCELERANT",
            "_TRIGGER",
            "_CONTRA",
        ):
            if indicator_key.endswith(suffix):
                return indicator_key[:-len(suffix)]

        return indicator_key

    def _preferred_class(
        self,
        evidence: dict[str, Any],
    ) -> str:
        text = " ".join(
            str(value or "")
            for value in (
                evidence.get("title"),
                evidence.get("raw_text"),
            )
        ).lower()

        contra_terms = {
            "reopened", "reopening", "de-escalation",
            "deescalation", "ceasefire", "restrictions lifted",
            "traffic restored", "transit restored",
        }

        trigger_terms = {
            "closure", "closed", "blockade", "blocked",
            "attack", "strike", "disruption", "disrupted",
            "interdiction", "mining",
        }

        accelerant_terms = {
            "intensify", "intensifies", "intensified",
            "expands", "expanded", "surge", "rising",
            "increase", "increased", "escalation",
        }

        if any(term in text for term in contra_terms):
            return "CONTRA"

        if any(term in text for term in trigger_terms):
            return "TRIGGER"

        if any(term in text for term in accelerant_terms):
            return "ACCELERANT"

        return "PRECURSOR"

    def score(
        self,
        *,
        evidence: dict[str, Any],
        indicator: dict[str, Any],
        mapping: dict[str, Any],
    ) -> IndicatorMatch | None:
        if self._blocked_evidence(evidence):
            return None

        lexical, semantic, matched_terms = self._lexical_scores(
            evidence=evidence,
            indicator=indicator,
            mapping=mapping,
        )

        if not matched_terms:
            return None

        reliability = self._source_reliability(evidence)
        freshness = self._freshness_score(evidence)
        corroboration = self._corroboration_score(evidence)

        indicator_class = str(
            mapping.get("indicator_class")
            or indicator.get("default_class")
            or "PRECURSOR"
        ).upper()

        preferred_class = self._preferred_class(evidence)

        class_alignment = (
            1.0
            if indicator_class == preferred_class
            else 0.35
        )

        contradiction_penalty = (
            0.15
            if (
                indicator_class == "CONTRA"
                and preferred_class != "CONTRA"
            )
            else 0.0
        )

        final_score = (
            lexical * 0.45
            + semantic * 0.25
            + reliability * 0.10
            + freshness * 0.08
            + corroboration * 0.04
            + class_alignment * 0.08
            - contradiction_penalty
        )

        # Production relevance gate. Source quality and freshness may
        # strengthen a relevant match but cannot rescue a weak one.
        if final_score < 0.44:
            return None

        return IndicatorMatch(
            indicator_key=indicator["indicator_key"],
            score=round(self._bounded(final_score), 6),
            matched_terms=matched_terms[:12],
            polarity=self.CLASS_POLARITY.get(
                indicator_class,
                "NEUTRAL",
            ),
            score_breakdown={
                "lexical_relevance": round(lexical, 4),
                "semantic_similarity": round(semantic, 4),
                "source_reliability": round(reliability, 4),
                "freshness": round(freshness, 4),
                "corroboration": round(corroboration, 4),
                "class_alignment": round(class_alignment, 4),
                "contradiction_penalty": round(
                    contradiction_penalty,
                    4,
                ),
                "final_score": round(
                    self._bounded(final_score),
                    4,
                ),
            },
        )

    def rank_for_evidence(
        self,
        *,
        evidence: dict[str, Any],
        mappings: list[dict[str, Any]],
        limit: int = 4,
    ) -> list[tuple[dict[str, Any], IndicatorMatch]]:
        best_by_concept: dict[
            str,
            tuple[dict[str, Any], IndicatorMatch],
        ] = {}

        for mapping in mappings:
            indicator = (
                mapping.get("sews_indicator_definitions")
                or {}
            )

            match = self.score(
                evidence=evidence,
                indicator=indicator,
                mapping=mapping,
            )

            if match is None:
                continue

            concept_key = self._concept_key(
                mapping["indicator_key"]
            )

            current = best_by_concept.get(concept_key)

            if (
                current is None
                or match.score > current[1].score
            ):
                best_by_concept[concept_key] = (
                    mapping,
                    match,
                )

        ranked = sorted(
            best_by_concept.values(),
            key=lambda item: (
                item[1].score,
                float(item[0].get("weight") or 1.0),
            ),
            reverse=True,
        )

        return ranked[:limit]

    def match(
        self,
        *,
        evidence: dict[str, Any],
        indicator: dict[str, Any],
        mapping: dict[str, Any],
    ) -> IndicatorMatch | None:
        return self.score(
            evidence=evidence,
            indicator=indicator,
            mapping=mapping,
        )
