from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from app.agents.base_agent import AgentSignal


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass
class EvidencePacket:
    """
    Canonical SIAM evidence container.

    Wraps processed AgentSignals together with analytical metadata
    generated by the Regional Evidence Processing Pipeline (REPP).
    """

    signals: list[AgentSignal]

    region: str | None = None

    total_signals: int = 0
    unique_countries: int = 0
    unique_sources: int = 0

    average_quality_score: float = 0.0
    average_confidence: float = 0.0
    average_freshness_score: float = 0.0

    country_breakdown: dict[str, int] = field(default_factory=dict)
    source_breakdown: dict[str, int] = field(default_factory=dict)

    processing_summary: dict[str, int] = field(default_factory=dict)

    generated_at: str = field(default_factory=utc_now_iso)

    @classmethod
    def from_signals(
        cls,
        signals: list[AgentSignal],
        *,
        region: str | None = None,
        processing_summary: dict[str, int] | None = None,
    ) -> "EvidencePacket":

        countries = Counter()
        sources = Counter()

        quality_scores = []
        freshness_scores = []
        confidence_scores = []

        for signal in signals:
            if signal.country_iso3:
                countries[signal.country_iso3] += 1

            if signal.source_key:
                sources[signal.source_key] += 1

            quality_scores.append(
                float(
                    getattr(
                        signal,
                        "siam_quality_score",
                        0.0,
                    )
                )
            )

            freshness_scores.append(
                float(
                    getattr(
                        signal,
                        "siam_freshness_score",
                        0.0,
                    )
                )
            )

            confidence_scores.append(
                float(signal.confidence or 0)
            )

        def avg(values: list[float]) -> float:
            return (
                round(sum(values) / len(values), 2)
                if values
                else 0.0
            )

        return cls(
            signals=signals,
            region=region,
            total_signals=len(signals),
            unique_countries=len(countries),
            unique_sources=len(sources),
            average_quality_score=avg(quality_scores),
            average_confidence=avg(confidence_scores),
            average_freshness_score=avg(freshness_scores),
            country_breakdown=dict(countries),
            source_breakdown=dict(sources),
            processing_summary=processing_summary or {},
        )
